kind: Secret
apiVersion: v1
metadata:
  name: {{ template "cockroachdb.fullname" . }}-users
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" $ }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  sql: {{ include "cockroachdb.update.sql" . | b64enc | quote }}